// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: channel_health.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const acquireChannelProbe = `-- name: AcquireChannelProbe :one
INSERT INTO channel_breaker_probes (channel_id, lease_id, leased_until)
VALUES ($1, gen_random_uuid(), now() + $2::integer * interval '1 second')
ON CONFLICT (channel_id) DO UPDATE
SET lease_id = gen_random_uuid(), leased_until = EXCLUDED.leased_until
WHERE channel_breaker_probes.leased_until <= now()
RETURNING lease_id::text
`

type AcquireChannelProbeParams struct {
	ChannelID    int64 `json:"channel_id"`
	LeaseSeconds int32 `json:"lease_seconds"`
}

func (q *Queries) AcquireChannelProbe(ctx context.Context, arg AcquireChannelProbeParams) (string, error) {
	row := q.db.QueryRow(ctx, acquireChannelProbe, arg.ChannelID, arg.LeaseSeconds)
	var lease_id string
	err := row.Scan(&lease_id)
	return lease_id, err
}

const deleteChannelHealthBuckets = `-- name: DeleteChannelHealthBuckets :exec
DELETE FROM channel_health_buckets WHERE channel_id = $1
`

func (q *Queries) DeleteChannelHealthBuckets(ctx context.Context, channelID int64) error {
	_, err := q.db.Exec(ctx, deleteChannelHealthBuckets, channelID)
	return err
}

const deleteChannelProbe = `-- name: DeleteChannelProbe :exec
DELETE FROM channel_breaker_probes WHERE channel_id = $1
`

func (q *Queries) DeleteChannelProbe(ctx context.Context, channelID int64) error {
	_, err := q.db.Exec(ctx, deleteChannelProbe, channelID)
	return err
}

const deleteStaleChannelHealthBuckets = `-- name: DeleteStaleChannelHealthBuckets :execrows
DELETE FROM channel_health_buckets WHERE bucket_start < $1
`

func (q *Queries) DeleteStaleChannelHealthBuckets(ctx context.Context, before pgtype.Timestamptz) (int64, error) {
	result, err := q.db.Exec(ctx, deleteStaleChannelHealthBuckets, before)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteUserBreakerConfig = `-- name: DeleteUserBreakerConfig :execrows
DELETE FROM user_breaker_configs WHERE owner_user_id = $1
`

func (q *Queries) DeleteUserBreakerConfig(ctx context.Context, ownerUserID int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteUserBreakerConfig, ownerUserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const ensureChannelHealth = `-- name: EnsureChannelHealth :exec
INSERT INTO channel_health (channel_id)
VALUES ($1)
ON CONFLICT (channel_id) DO NOTHING
`

func (q *Queries) EnsureChannelHealth(ctx context.Context, channelID int64) error {
	_, err := q.db.Exec(ctx, ensureChannelHealth, channelID)
	return err
}

const getChannelHealth = `-- name: GetChannelHealth :one
SELECT channel_id, state, consecutive_failures, success_count, failure_count, opened_at, updated_at
FROM channel_health
WHERE channel_id = $1
`

func (q *Queries) GetChannelHealth(ctx context.Context, channelID int64) (ChannelHealth, error) {
	row := q.db.QueryRow(ctx, getChannelHealth, channelID)
	var i ChannelHealth
	err := row.Scan(
		&i.ChannelID,
		&i.State,
		&i.ConsecutiveFailures,
		&i.SuccessCount,
		&i.FailureCount,
		&i.OpenedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getChannelHealthForUpdate = `-- name: GetChannelHealthForUpdate :one
SELECT channel_id, state, consecutive_failures, success_count, failure_count, opened_at, updated_at
FROM channel_health
WHERE channel_id = $1
FOR UPDATE
`

func (q *Queries) GetChannelHealthForUpdate(ctx context.Context, channelID int64) (ChannelHealth, error) {
	row := q.db.QueryRow(ctx, getChannelHealthForUpdate, channelID)
	var i ChannelHealth
	err := row.Scan(
		&i.ChannelID,
		&i.State,
		&i.ConsecutiveFailures,
		&i.SuccessCount,
		&i.FailureCount,
		&i.OpenedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserBreakerConfig = `-- name: GetUserBreakerConfig :one
SELECT window_seconds, minimum_samples, error_rate_percent, timeout_rate_percent, cooldown_seconds
FROM user_breaker_configs
WHERE owner_user_id = $1
`

type GetUserBreakerConfigRow struct {
	WindowSeconds      int32 `json:"window_seconds"`
	MinimumSamples     int32 `json:"minimum_samples"`
	ErrorRatePercent   int32 `json:"error_rate_percent"`
	TimeoutRatePercent int32 `json:"timeout_rate_percent"`
	CooldownSeconds    int32 `json:"cooldown_seconds"`
}

func (q *Queries) GetUserBreakerConfig(ctx context.Context, ownerUserID int64) (GetUserBreakerConfigRow, error) {
	row := q.db.QueryRow(ctx, getUserBreakerConfig, ownerUserID)
	var i GetUserBreakerConfigRow
	err := row.Scan(
		&i.WindowSeconds,
		&i.MinimumSamples,
		&i.ErrorRatePercent,
		&i.TimeoutRatePercent,
		&i.CooldownSeconds,
	)
	return i, err
}

const listChannelHealth = `-- name: ListChannelHealth :many
SELECT c.id AS channel_id,
    COALESCE(h.state, 'closed')::text AS state,
    COALESCE(h.consecutive_failures, 0)::integer AS consecutive_failures,
    COALESCE(h.success_count, 0)::bigint AS success_count,
    COALESCE(h.failure_count, 0)::bigint AS failure_count,
    h.opened_at,
    COALESCE(h.updated_at, c.updated_at)::timestamptz AS updated_at
FROM channels c
LEFT JOIN channel_health h ON h.channel_id = c.id
WHERE c.owner_user_id = $1
ORDER BY c.id
`

type ListChannelHealthRow struct {
	ChannelID           int64              `json:"channel_id"`
	State               string             `json:"state"`
	ConsecutiveFailures int32              `json:"consecutive_failures"`
	SuccessCount        int64              `json:"success_count"`
	FailureCount        int64              `json:"failure_count"`
	OpenedAt            pgtype.Timestamptz `json:"opened_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListChannelHealth(ctx context.Context, ownerUserID int64) ([]ListChannelHealthRow, error) {
	rows, err := q.db.Query(ctx, listChannelHealth, ownerUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListChannelHealthRow{}
	for rows.Next() {
		var i ListChannelHealthRow
		if err := rows.Scan(
			&i.ChannelID,
			&i.State,
			&i.ConsecutiveFailures,
			&i.SuccessCount,
			&i.FailureCount,
			&i.OpenedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const releaseChannelProbe = `-- name: ReleaseChannelProbe :execrows
DELETE FROM channel_breaker_probes
WHERE channel_id = $1 AND lease_id = $2::text::uuid
`

type ReleaseChannelProbeParams struct {
	ChannelID int64  `json:"channel_id"`
	LeaseID   string `json:"lease_id"`
}

func (q *Queries) ReleaseChannelProbe(ctx context.Context, arg ReleaseChannelProbeParams) (int64, error) {
	result, err := q.db.Exec(ctx, releaseChannelProbe, arg.ChannelID, arg.LeaseID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const resetChannelHealthState = `-- name: ResetChannelHealthState :exec
UPDATE channel_health
SET state = 'closed',
    consecutive_failures = 0,
    opened_at = NULL,
    updated_at = now()
WHERE channel_id = $1
`

func (q *Queries) ResetChannelHealthState(ctx context.Context, channelID int64) error {
	_, err := q.db.Exec(ctx, resetChannelHealthState, channelID)
	return err
}

const sumChannelHealthWindow = `-- name: SumChannelHealthWindow :one
SELECT
    COALESCE(SUM(requests), 0)::bigint AS requests,
    COALESCE(SUM(errors), 0)::bigint AS errors,
    COALESCE(SUM(timeouts), 0)::bigint AS timeouts
FROM channel_health_buckets
WHERE channel_id = $1 AND bucket_start >= $2
`

type SumChannelHealthWindowParams struct {
	ChannelID int64              `json:"channel_id"`
	Since     pgtype.Timestamptz `json:"since"`
}

type SumChannelHealthWindowRow struct {
	Requests int64 `json:"requests"`
	Errors   int64 `json:"errors"`
	Timeouts int64 `json:"timeouts"`
}

func (q *Queries) SumChannelHealthWindow(ctx context.Context, arg SumChannelHealthWindowParams) (SumChannelHealthWindowRow, error) {
	row := q.db.QueryRow(ctx, sumChannelHealthWindow, arg.ChannelID, arg.Since)
	var i SumChannelHealthWindowRow
	err := row.Scan(&i.Requests, &i.Errors, &i.Timeouts)
	return i, err
}

const updateChannelHealth = `-- name: UpdateChannelHealth :execrows
UPDATE channel_health
SET state = $1,
    consecutive_failures = $2,
    success_count = $3,
    failure_count = $4,
    opened_at = $5,
    updated_at = now()
WHERE channel_id = $6
`

type UpdateChannelHealthParams struct {
	State               string             `json:"state"`
	ConsecutiveFailures int32              `json:"consecutive_failures"`
	SuccessCount        int64              `json:"success_count"`
	FailureCount        int64              `json:"failure_count"`
	OpenedAt            pgtype.Timestamptz `json:"opened_at"`
	ChannelID           int64              `json:"channel_id"`
}

func (q *Queries) UpdateChannelHealth(ctx context.Context, arg UpdateChannelHealthParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateChannelHealth,
		arg.State,
		arg.ConsecutiveFailures,
		arg.SuccessCount,
		arg.FailureCount,
		arg.OpenedAt,
		arg.ChannelID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertChannelHealthBucket = `-- name: UpsertChannelHealthBucket :exec
INSERT INTO channel_health_buckets (channel_id, bucket_start, requests, errors, timeouts)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (channel_id, bucket_start) DO UPDATE
SET requests = channel_health_buckets.requests + EXCLUDED.requests,
    errors = channel_health_buckets.errors + EXCLUDED.errors,
    timeouts = channel_health_buckets.timeouts + EXCLUDED.timeouts
`

type UpsertChannelHealthBucketParams struct {
	ChannelID   int64              `json:"channel_id"`
	BucketStart pgtype.Timestamptz `json:"bucket_start"`
	Requests    int64              `json:"requests"`
	Errors      int64              `json:"errors"`
	Timeouts    int64              `json:"timeouts"`
}

func (q *Queries) UpsertChannelHealthBucket(ctx context.Context, arg UpsertChannelHealthBucketParams) error {
	_, err := q.db.Exec(ctx, upsertChannelHealthBucket,
		arg.ChannelID,
		arg.BucketStart,
		arg.Requests,
		arg.Errors,
		arg.Timeouts,
	)
	return err
}

const upsertUserBreakerConfig = `-- name: UpsertUserBreakerConfig :exec
INSERT INTO user_breaker_configs (owner_user_id, window_seconds, minimum_samples, error_rate_percent, timeout_rate_percent, cooldown_seconds, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, now())
ON CONFLICT (owner_user_id) DO UPDATE
SET window_seconds = EXCLUDED.window_seconds,
    minimum_samples = EXCLUDED.minimum_samples,
    error_rate_percent = EXCLUDED.error_rate_percent,
    timeout_rate_percent = EXCLUDED.timeout_rate_percent,
    cooldown_seconds = EXCLUDED.cooldown_seconds,
    updated_at = now()
`

type UpsertUserBreakerConfigParams struct {
	OwnerUserID        int64 `json:"owner_user_id"`
	WindowSeconds      int32 `json:"window_seconds"`
	MinimumSamples     int32 `json:"minimum_samples"`
	ErrorRatePercent   int32 `json:"error_rate_percent"`
	TimeoutRatePercent int32 `json:"timeout_rate_percent"`
	CooldownSeconds    int32 `json:"cooldown_seconds"`
}

func (q *Queries) UpsertUserBreakerConfig(ctx context.Context, arg UpsertUserBreakerConfigParams) error {
	_, err := q.db.Exec(ctx, upsertUserBreakerConfig,
		arg.OwnerUserID,
		arg.WindowSeconds,
		arg.MinimumSamples,
		arg.ErrorRatePercent,
		arg.TimeoutRatePercent,
		arg.CooldownSeconds,
	)
	return err
}
