// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: channels.sql

package sqlc

import (
	"context"
)

const createChannel = `-- name: CreateChannel :one
INSERT INTO channels (owner_user_id, name, base_url, api_key_ciphertext, auth_type, status, weight, priority, balance)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    NULLIF($9, '')::numeric
)
RETURNING id
`

type CreateChannelParams struct {
	OwnerUserID      int64       `json:"owner_user_id"`
	Name             string      `json:"name"`
	BaseUrl          string      `json:"base_url"`
	ApiKeyCiphertext string      `json:"api_key_ciphertext"`
	AuthType         string      `json:"auth_type"`
	Status           int32       `json:"status"`
	Weight           int32       `json:"weight"`
	Priority         int32       `json:"priority"`
	Balance          interface{} `json:"balance"`
}

func (q *Queries) CreateChannel(ctx context.Context, arg CreateChannelParams) (int64, error) {
	row := q.db.QueryRow(ctx, createChannel,
		arg.OwnerUserID,
		arg.Name,
		arg.BaseUrl,
		arg.ApiKeyCiphertext,
		arg.AuthType,
		arg.Status,
		arg.Weight,
		arg.Priority,
		arg.Balance,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const deleteChannel = `-- name: DeleteChannel :execrows
DELETE FROM channels WHERE id = $1 AND owner_user_id = $2
`

type DeleteChannelParams struct {
	ID          int64 `json:"id"`
	OwnerUserID int64 `json:"owner_user_id"`
}

func (q *Queries) DeleteChannel(ctx context.Context, arg DeleteChannelParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteChannel, arg.ID, arg.OwnerUserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getChannel = `-- name: GetChannel :one
SELECT
    c.id,
    c.name,
    c.base_url,
    c.auth_type,
    c.status,
    c.weight,
    c.priority,
    COALESCE(c.balance::text, ''::text) AS balance,
    count(cm.id)::int AS model_count
FROM channels c
LEFT JOIN channel_models cm ON cm.channel_id = c.id
WHERE c.id = $1 AND c.owner_user_id = $2
GROUP BY c.id
`

type GetChannelParams struct {
	ID          int64 `json:"id"`
	OwnerUserID int64 `json:"owner_user_id"`
}

type GetChannelRow struct {
	ID         int64       `json:"id"`
	Name       string      `json:"name"`
	BaseUrl    string      `json:"base_url"`
	AuthType   string      `json:"auth_type"`
	Status     int32       `json:"status"`
	Weight     int32       `json:"weight"`
	Priority   int32       `json:"priority"`
	Balance    interface{} `json:"balance"`
	ModelCount int32       `json:"model_count"`
}

func (q *Queries) GetChannel(ctx context.Context, arg GetChannelParams) (GetChannelRow, error) {
	row := q.db.QueryRow(ctx, getChannel, arg.ID, arg.OwnerUserID)
	var i GetChannelRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.BaseUrl,
		&i.AuthType,
		&i.Status,
		&i.Weight,
		&i.Priority,
		&i.Balance,
		&i.ModelCount,
	)
	return i, err
}

const getChannelSecret = `-- name: GetChannelSecret :one
SELECT
    id,
    name,
    base_url,
    api_key_ciphertext,
    auth_type,
    status,
    weight,
    priority,
    COALESCE(balance::text, ''::text) AS balance
FROM channels
WHERE id = $1 AND owner_user_id = $2
`

type GetChannelSecretParams struct {
	ID          int64 `json:"id"`
	OwnerUserID int64 `json:"owner_user_id"`
}

type GetChannelSecretRow struct {
	ID               int64       `json:"id"`
	Name             string      `json:"name"`
	BaseUrl          string      `json:"base_url"`
	ApiKeyCiphertext string      `json:"api_key_ciphertext"`
	AuthType         string      `json:"auth_type"`
	Status           int32       `json:"status"`
	Weight           int32       `json:"weight"`
	Priority         int32       `json:"priority"`
	Balance          interface{} `json:"balance"`
}

func (q *Queries) GetChannelSecret(ctx context.Context, arg GetChannelSecretParams) (GetChannelSecretRow, error) {
	row := q.db.QueryRow(ctx, getChannelSecret, arg.ID, arg.OwnerUserID)
	var i GetChannelSecretRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.BaseUrl,
		&i.ApiKeyCiphertext,
		&i.AuthType,
		&i.Status,
		&i.Weight,
		&i.Priority,
		&i.Balance,
	)
	return i, err
}

const listChannels = `-- name: ListChannels :many
SELECT
    c.id,
    c.name,
    c.base_url,
    c.auth_type,
    c.status,
    c.weight,
    c.priority,
    COALESCE(c.balance::text, ''::text) AS balance,
    count(cm.id)::int AS model_count
FROM channels c
LEFT JOIN channel_models cm ON cm.channel_id = c.id
WHERE c.owner_user_id = $1
GROUP BY c.id
ORDER BY c.id
`

type ListChannelsRow struct {
	ID         int64       `json:"id"`
	Name       string      `json:"name"`
	BaseUrl    string      `json:"base_url"`
	AuthType   string      `json:"auth_type"`
	Status     int32       `json:"status"`
	Weight     int32       `json:"weight"`
	Priority   int32       `json:"priority"`
	Balance    interface{} `json:"balance"`
	ModelCount int32       `json:"model_count"`
}

func (q *Queries) ListChannels(ctx context.Context, ownerUserID int64) ([]ListChannelsRow, error) {
	rows, err := q.db.Query(ctx, listChannels, ownerUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListChannelsRow{}
	for rows.Next() {
		var i ListChannelsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.BaseUrl,
			&i.AuthType,
			&i.Status,
			&i.Weight,
			&i.Priority,
			&i.Balance,
			&i.ModelCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockChannel = `-- name: LockChannel :one
SELECT id FROM channels
WHERE id = $1 AND owner_user_id = $2
FOR UPDATE
`

type LockChannelParams struct {
	ID          int64 `json:"id"`
	OwnerUserID int64 `json:"owner_user_id"`
}

func (q *Queries) LockChannel(ctx context.Context, arg LockChannelParams) (int64, error) {
	row := q.db.QueryRow(ctx, lockChannel, arg.ID, arg.OwnerUserID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const updateChannel = `-- name: UpdateChannel :execrows
UPDATE channels
SET name = $1,
    base_url = $2,
    auth_type = $3,
    status = $4,
    weight = $5,
    priority = $6,
    balance = NULLIF($7, '')::numeric,
    api_key_ciphertext = COALESCE(NULLIF($8, ''), api_key_ciphertext),
    updated_at = now()
WHERE id = $9 AND owner_user_id = $10
`

type UpdateChannelParams struct {
	Name             string      `json:"name"`
	BaseUrl          string      `json:"base_url"`
	AuthType         string      `json:"auth_type"`
	Status           int32       `json:"status"`
	Weight           int32       `json:"weight"`
	Priority         int32       `json:"priority"`
	Balance          interface{} `json:"balance"`
	ApiKeyCiphertext interface{} `json:"api_key_ciphertext"`
	ID               int64       `json:"id"`
	OwnerUserID      int64       `json:"owner_user_id"`
}

func (q *Queries) UpdateChannel(ctx context.Context, arg UpdateChannelParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateChannel,
		arg.Name,
		arg.BaseUrl,
		arg.AuthType,
		arg.Status,
		arg.Weight,
		arg.Priority,
		arg.Balance,
		arg.ApiKeyCiphertext,
		arg.ID,
		arg.OwnerUserID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateChannelBalance = `-- name: UpdateChannelBalance :execrows
UPDATE channels
SET balance = NULLIF($1, '')::numeric, updated_at = now()
WHERE id = $2 AND owner_user_id = $3
`

type UpdateChannelBalanceParams struct {
	Balance     interface{} `json:"balance"`
	ID          int64       `json:"id"`
	OwnerUserID int64       `json:"owner_user_id"`
}

func (q *Queries) UpdateChannelBalance(ctx context.Context, arg UpdateChannelBalanceParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateChannelBalance, arg.Balance, arg.ID, arg.OwnerUserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateChannelStatus = `-- name: UpdateChannelStatus :execrows
UPDATE channels
SET status = $1, updated_at = now()
WHERE id = $2 AND owner_user_id = $3
`

type UpdateChannelStatusParams struct {
	Status      int32 `json:"status"`
	ID          int64 `json:"id"`
	OwnerUserID int64 `json:"owner_user_id"`
}

func (q *Queries) UpdateChannelStatus(ctx context.Context, arg UpdateChannelStatusParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateChannelStatus, arg.Status, arg.ID, arg.OwnerUserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
