// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: models.sql

package sqlc

import (
	"context"
)

const channelUpstreamExists = `-- name: ChannelUpstreamExists :one
SELECT 1 FROM channel_models cm
JOIN channels c ON c.id = cm.channel_id
WHERE cm.channel_id = $1
  AND cm.upstream_model = $2
  AND c.owner_user_id = $3
LIMIT 1
`

type ChannelUpstreamExistsParams struct {
	ChannelID     int64  `json:"channel_id"`
	UpstreamModel string `json:"upstream_model"`
	OwnerUserID   int64  `json:"owner_user_id"`
}

func (q *Queries) ChannelUpstreamExists(ctx context.Context, arg ChannelUpstreamExistsParams) (int32, error) {
	row := q.db.QueryRow(ctx, channelUpstreamExists, arg.ChannelID, arg.UpstreamModel, arg.OwnerUserID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const createChannelModel = `-- name: CreateChannelModel :one
INSERT INTO channel_models (channel_id, model_name, upstream_model, enabled)
VALUES ($1, $2, $3, $4)
RETURNING id, model_name, upstream_model, enabled
`

type CreateChannelModelParams struct {
	ChannelID     int64  `json:"channel_id"`
	ModelName     string `json:"model_name"`
	UpstreamModel string `json:"upstream_model"`
	Enabled       bool   `json:"enabled"`
}

type CreateChannelModelRow struct {
	ID            int64  `json:"id"`
	ModelName     string `json:"model_name"`
	UpstreamModel string `json:"upstream_model"`
	Enabled       bool   `json:"enabled"`
}

func (q *Queries) CreateChannelModel(ctx context.Context, arg CreateChannelModelParams) (CreateChannelModelRow, error) {
	row := q.db.QueryRow(ctx, createChannelModel,
		arg.ChannelID,
		arg.ModelName,
		arg.UpstreamModel,
		arg.Enabled,
	)
	var i CreateChannelModelRow
	err := row.Scan(
		&i.ID,
		&i.ModelName,
		&i.UpstreamModel,
		&i.Enabled,
	)
	return i, err
}

const deleteChannelModel = `-- name: DeleteChannelModel :execrows
DELETE FROM channel_models WHERE channel_id = $1 AND id = $2
`

type DeleteChannelModelParams struct {
	ChannelID int64 `json:"channel_id"`
	ID        int64 `json:"id"`
}

func (q *Queries) DeleteChannelModel(ctx context.Context, arg DeleteChannelModelParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteChannelModel, arg.ChannelID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getChannelModel = `-- name: GetChannelModel :one
SELECT cm.id, cm.model_name, cm.upstream_model, cm.enabled
FROM channel_models cm
JOIN channels c ON c.id = cm.channel_id
WHERE cm.channel_id = $1
  AND cm.model_name = $2
  AND c.owner_user_id = $3
`

type GetChannelModelParams struct {
	ChannelID   int64  `json:"channel_id"`
	ModelName   string `json:"model_name"`
	OwnerUserID int64  `json:"owner_user_id"`
}

type GetChannelModelRow struct {
	ID            int64  `json:"id"`
	ModelName     string `json:"model_name"`
	UpstreamModel string `json:"upstream_model"`
	Enabled       bool   `json:"enabled"`
}

func (q *Queries) GetChannelModel(ctx context.Context, arg GetChannelModelParams) (GetChannelModelRow, error) {
	row := q.db.QueryRow(ctx, getChannelModel, arg.ChannelID, arg.ModelName, arg.OwnerUserID)
	var i GetChannelModelRow
	err := row.Scan(
		&i.ID,
		&i.ModelName,
		&i.UpstreamModel,
		&i.Enabled,
	)
	return i, err
}

const getChannelModelByID = `-- name: GetChannelModelByID :one
SELECT cm.id, cm.model_name, cm.upstream_model, cm.enabled
FROM channel_models cm
WHERE cm.channel_id = $1 AND cm.id = $2
`

type GetChannelModelByIDParams struct {
	ChannelID int64 `json:"channel_id"`
	ID        int64 `json:"id"`
}

type GetChannelModelByIDRow struct {
	ID            int64  `json:"id"`
	ModelName     string `json:"model_name"`
	UpstreamModel string `json:"upstream_model"`
	Enabled       bool   `json:"enabled"`
}

func (q *Queries) GetChannelModelByID(ctx context.Context, arg GetChannelModelByIDParams) (GetChannelModelByIDRow, error) {
	row := q.db.QueryRow(ctx, getChannelModelByID, arg.ChannelID, arg.ID)
	var i GetChannelModelByIDRow
	err := row.Scan(
		&i.ID,
		&i.ModelName,
		&i.UpstreamModel,
		&i.Enabled,
	)
	return i, err
}

const listCatalogModels = `-- name: ListCatalogModels :many
SELECT
    cm.model_name,
    c.id AS channel_id,
    c.name AS channel_name,
    cm.upstream_model,
    cm.enabled
FROM channel_models cm
JOIN channels c ON c.id = cm.channel_id
WHERE c.owner_user_id = $1
  AND ($2::boolean = false OR cm.enabled = true)
ORDER BY cm.model_name, c.priority DESC, c.weight DESC, c.id
`

type ListCatalogModelsParams struct {
	OwnerUserID int64 `json:"owner_user_id"`
	EnabledOnly bool  `json:"enabled_only"`
}

type ListCatalogModelsRow struct {
	ModelName     string `json:"model_name"`
	ChannelID     int64  `json:"channel_id"`
	ChannelName   string `json:"channel_name"`
	UpstreamModel string `json:"upstream_model"`
	Enabled       bool   `json:"enabled"`
}

func (q *Queries) ListCatalogModels(ctx context.Context, arg ListCatalogModelsParams) ([]ListCatalogModelsRow, error) {
	rows, err := q.db.Query(ctx, listCatalogModels, arg.OwnerUserID, arg.EnabledOnly)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCatalogModelsRow{}
	for rows.Next() {
		var i ListCatalogModelsRow
		if err := rows.Scan(
			&i.ModelName,
			&i.ChannelID,
			&i.ChannelName,
			&i.UpstreamModel,
			&i.Enabled,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChannelModels = `-- name: ListChannelModels :many
SELECT cm.id, cm.model_name, cm.upstream_model, cm.enabled
FROM channel_models cm
JOIN channels c ON c.id = cm.channel_id
WHERE cm.channel_id = $1 AND c.owner_user_id = $2
ORDER BY cm.id
`

type ListChannelModelsParams struct {
	ChannelID   int64 `json:"channel_id"`
	OwnerUserID int64 `json:"owner_user_id"`
}

type ListChannelModelsRow struct {
	ID            int64  `json:"id"`
	ModelName     string `json:"model_name"`
	UpstreamModel string `json:"upstream_model"`
	Enabled       bool   `json:"enabled"`
}

func (q *Queries) ListChannelModels(ctx context.Context, arg ListChannelModelsParams) ([]ListChannelModelsRow, error) {
	rows, err := q.db.Query(ctx, listChannelModels, arg.ChannelID, arg.OwnerUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListChannelModelsRow{}
	for rows.Next() {
		var i ListChannelModelsRow
		if err := rows.Scan(
			&i.ID,
			&i.ModelName,
			&i.UpstreamModel,
			&i.Enabled,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRouteCandidates = `-- name: ListRouteCandidates :many
SELECT
    c.id AS channel_id,
    c.name AS channel_name,
    cm.upstream_model,
    c.priority,
    c.weight,
    COALESCE(c.balance::text, '') AS balance,
    CASE
        WHEN h.state = 'open'
            AND h.opened_at + ($1::int * interval '1 second') <= now()
        THEN 'half-open'
        ELSE COALESCE(h.state, 'closed')
    END::text AS health_state
FROM channel_models cm
JOIN channels c ON c.id = cm.channel_id
LEFT JOIN channel_health h ON h.channel_id = c.id
WHERE cm.model_name = $2 AND cm.enabled = true AND c.status = 1
  AND c.owner_user_id = $3

  AND NOT (
      COALESCE(h.state, 'closed') = 'open'
      AND (
          h.opened_at IS NULL
          OR h.opened_at + ($1::int * interval '1 second') > now()
      )
  )
ORDER BY c.priority DESC, c.weight DESC, c.id
`

type ListRouteCandidatesParams struct {
	DefaultCooldownSeconds int32  `json:"default_cooldown_seconds"`
	ModelName              string `json:"model_name"`
	OwnerUserID            int64  `json:"owner_user_id"`
}

type ListRouteCandidatesRow struct {
	ChannelID     int64       `json:"channel_id"`
	ChannelName   string      `json:"channel_name"`
	UpstreamModel string      `json:"upstream_model"`
	Priority      int32       `json:"priority"`
	Weight        int32       `json:"weight"`
	Balance       interface{} `json:"balance"`
	HealthState   string      `json:"health_state"`
}

func (q *Queries) ListRouteCandidates(ctx context.Context, arg ListRouteCandidatesParams) ([]ListRouteCandidatesRow, error) {
	rows, err := q.db.Query(ctx, listRouteCandidates, arg.DefaultCooldownSeconds, arg.ModelName, arg.OwnerUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRouteCandidatesRow{}
	for rows.Next() {
		var i ListRouteCandidatesRow
		if err := rows.Scan(
			&i.ChannelID,
			&i.ChannelName,
			&i.UpstreamModel,
			&i.Priority,
			&i.Weight,
			&i.Balance,
			&i.HealthState,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateChannelModel = `-- name: UpdateChannelModel :one
UPDATE channel_models
SET model_name = COALESCE(NULLIF($1, ''), model_name),
    enabled = $2,
    updated_at = now()
WHERE channel_id = $3 AND id = $4
RETURNING id, model_name, upstream_model, enabled
`

type UpdateChannelModelParams struct {
	ModelName interface{} `json:"model_name"`
	Enabled   bool        `json:"enabled"`
	ChannelID int64       `json:"channel_id"`
	ID        int64       `json:"id"`
}

type UpdateChannelModelRow struct {
	ID            int64  `json:"id"`
	ModelName     string `json:"model_name"`
	UpstreamModel string `json:"upstream_model"`
	Enabled       bool   `json:"enabled"`
}

// The upstream (real) model name is set by the upstream and cannot change;
// only the public alias and enabled flag are updated.
func (q *Queries) UpdateChannelModel(ctx context.Context, arg UpdateChannelModelParams) (UpdateChannelModelRow, error) {
	row := q.db.QueryRow(ctx, updateChannelModel,
		arg.ModelName,
		arg.Enabled,
		arg.ChannelID,
		arg.ID,
	)
	var i UpdateChannelModelRow
	err := row.Scan(
		&i.ID,
		&i.ModelName,
		&i.UpstreamModel,
		&i.Enabled,
	)
	return i, err
}
