// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: pricing.sql

package sqlc

import (
	"context"
)

const deletePricing = `-- name: DeletePricing :exec
DELETE FROM model_pricing WHERE channel_id = $1 AND upstream_model = $2
`

type DeletePricingParams struct {
	ChannelID     int64  `json:"channel_id"`
	UpstreamModel string `json:"upstream_model"`
}

func (q *Queries) DeletePricing(ctx context.Context, arg DeletePricingParams) error {
	_, err := q.db.Exec(ctx, deletePricing, arg.ChannelID, arg.UpstreamModel)
	return err
}

const getPricing = `-- name: GetPricing :one
SELECT
    p.id,
    p.channel_id,
    c.name AS channel_name,
    p.upstream_model,
    p.input_price_per_1m::text AS input_price_per_1m,
    p.output_price_per_1m::text AS output_price_per_1m,
    COALESCE(p.cached_input_price_per_1m::text, ''::text) AS cached_input_price_per_1m,
    p.currency
FROM model_pricing p
JOIN channels c ON c.id = p.channel_id
WHERE p.channel_id = $1 AND p.upstream_model = $2
`

type GetPricingParams struct {
	ChannelID     int64  `json:"channel_id"`
	UpstreamModel string `json:"upstream_model"`
}

type GetPricingRow struct {
	ID                    int64       `json:"id"`
	ChannelID             int64       `json:"channel_id"`
	ChannelName           string      `json:"channel_name"`
	UpstreamModel         string      `json:"upstream_model"`
	InputPricePer1m       string      `json:"input_price_per_1m"`
	OutputPricePer1m      string      `json:"output_price_per_1m"`
	CachedInputPricePer1m interface{} `json:"cached_input_price_per_1m"`
	Currency              string      `json:"currency"`
}

func (q *Queries) GetPricing(ctx context.Context, arg GetPricingParams) (GetPricingRow, error) {
	row := q.db.QueryRow(ctx, getPricing, arg.ChannelID, arg.UpstreamModel)
	var i GetPricingRow
	err := row.Scan(
		&i.ID,
		&i.ChannelID,
		&i.ChannelName,
		&i.UpstreamModel,
		&i.InputPricePer1m,
		&i.OutputPricePer1m,
		&i.CachedInputPricePer1m,
		&i.Currency,
	)
	return i, err
}

const listPricing = `-- name: ListPricing :many
SELECT
    p.id,
    p.channel_id,
    c.name AS channel_name,
    p.upstream_model,
    p.input_price_per_1m::text AS input_price_per_1m,
    p.output_price_per_1m::text AS output_price_per_1m,
    COALESCE(p.cached_input_price_per_1m::text, ''::text) AS cached_input_price_per_1m,
    p.currency
FROM model_pricing p
JOIN channels c ON c.id = p.channel_id
WHERE c.owner_user_id = $1
ORDER BY p.id
`

type ListPricingRow struct {
	ID                    int64       `json:"id"`
	ChannelID             int64       `json:"channel_id"`
	ChannelName           string      `json:"channel_name"`
	UpstreamModel         string      `json:"upstream_model"`
	InputPricePer1m       string      `json:"input_price_per_1m"`
	OutputPricePer1m      string      `json:"output_price_per_1m"`
	CachedInputPricePer1m interface{} `json:"cached_input_price_per_1m"`
	Currency              string      `json:"currency"`
}

func (q *Queries) ListPricing(ctx context.Context, ownerUserID int64) ([]ListPricingRow, error) {
	rows, err := q.db.Query(ctx, listPricing, ownerUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPricingRow{}
	for rows.Next() {
		var i ListPricingRow
		if err := rows.Scan(
			&i.ID,
			&i.ChannelID,
			&i.ChannelName,
			&i.UpstreamModel,
			&i.InputPricePer1m,
			&i.OutputPricePer1m,
			&i.CachedInputPricePer1m,
			&i.Currency,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertPricing = `-- name: UpsertPricing :one
INSERT INTO model_pricing (channel_id, upstream_model, input_price_per_1m, output_price_per_1m, cached_input_price_per_1m, currency)
VALUES (
    $1,
    $2,
    NULLIF($3, '')::numeric,
    NULLIF($4, '')::numeric,
    NULLIF($5, '')::numeric,
    $6
)
ON CONFLICT (channel_id, upstream_model)
DO UPDATE SET
    input_price_per_1m = EXCLUDED.input_price_per_1m,
    output_price_per_1m = EXCLUDED.output_price_per_1m,
    cached_input_price_per_1m = EXCLUDED.cached_input_price_per_1m,
    currency = EXCLUDED.currency,
    updated_at = now()
RETURNING id
`

type UpsertPricingParams struct {
	ChannelID             int64       `json:"channel_id"`
	UpstreamModel         string      `json:"upstream_model"`
	InputPricePer1m       interface{} `json:"input_price_per_1m"`
	OutputPricePer1m      interface{} `json:"output_price_per_1m"`
	CachedInputPricePer1m interface{} `json:"cached_input_price_per_1m"`
	Currency              string      `json:"currency"`
}

func (q *Queries) UpsertPricing(ctx context.Context, arg UpsertPricingParams) (int64, error) {
	row := q.db.QueryRow(ctx, upsertPricing,
		arg.ChannelID,
		arg.UpstreamModel,
		arg.InputPricePer1m,
		arg.OutputPricePer1m,
		arg.CachedInputPricePer1m,
		arg.Currency,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}
