// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AggregateUsageByAPIKey(ctx context.Context, arg AggregateUsageByAPIKeyParams) ([]AggregateUsageByAPIKeyRow, error)
	AggregateUsageByChannel(ctx context.Context, arg AggregateUsageByChannelParams) ([]AggregateUsageByChannelRow, error)
	AggregateUsageByModel(ctx context.Context, arg AggregateUsageByModelParams) ([]AggregateUsageByModelRow, error)
	AggregateUsageByUser(ctx context.Context, arg AggregateUsageByUserParams) ([]AggregateUsageByUserRow, error)
	CountBalanceTransactions(ctx context.Context, userID int64) (int32, error)
	CountKeys(ctx context.Context) (int32, error)
	CountRateLimitRules(ctx context.Context, arg CountRateLimitRulesParams) (int32, error)
	CountRequestsSince(ctx context.Context, arg CountRequestsSinceParams) (int32, error)
	CountStatsDaily(ctx context.Context, arg CountStatsDailyParams) (int32, error)
	CountUsageLogs(ctx context.Context, arg CountUsageLogsParams) (int32, error)
	CountUserKeys(ctx context.Context, userID int64) (int32, error)
	CountUsers(ctx context.Context) (int32, error)
	CreateBalanceTransaction(ctx context.Context, arg CreateBalanceTransactionParams) (int64, error)
	CreateChannel(ctx context.Context, arg CreateChannelParams) (int64, error)
	CreateChannelModel(ctx context.Context, arg CreateChannelModelParams) (CreateChannelModelRow, error)
	CreateKey(ctx context.Context, arg CreateKeyParams) (int64, error)
	CreateQuotaPolicy(ctx context.Context, arg CreateQuotaPolicyParams) (int64, error)
	CreateRateLimitRule(ctx context.Context, arg CreateRateLimitRuleParams) (int64, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (int64, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (int64, error)
	CreateUserBalance(ctx context.Context, userID int64) error
	CreateUserWithCredentials(ctx context.Context, arg CreateUserWithCredentialsParams) (int64, error)
	DeleteChannel(ctx context.Context, arg DeleteChannelParams) (int64, error)
	DeleteChannelBreakerConfig(ctx context.Context, channelID int64) (int64, error)
	DeleteChannelHealth(ctx context.Context, channelID int64) (int64, error)
	DeleteChannelModel(ctx context.Context, arg DeleteChannelModelParams) (int64, error)
	DeleteExpiredSessions(ctx context.Context, maxRows int32) (int64, error)
	DeleteKey(ctx context.Context, arg DeleteKeyParams) (int64, error)
	DeletePricing(ctx context.Context, arg DeletePricingParams) error
	DeleteQuotaPolicy(ctx context.Context, arg DeleteQuotaPolicyParams) (int64, error)
	DeleteRateLimitRule(ctx context.Context, arg DeleteRateLimitRuleParams) (int64, error)
	DeleteSessionByTokenHash(ctx context.Context, tokenHash string) (int64, error)
	DeleteStaleChannelHealthBuckets(ctx context.Context, before pgtype.Timestamptz) (int64, error)
	DeleteUser(ctx context.Context, id int64) (int64, error)
	EnsureChannelHealth(ctx context.Context, channelID int64) error
	GetAccountByID(ctx context.Context, id int64) (GetAccountByIDRow, error)
	GetAuthContextByKeyHash(ctx context.Context, keyHash string) (GetAuthContextByKeyHashRow, error)
	GetBalanceTransactionByOrder(ctx context.Context, arg GetBalanceTransactionByOrderParams) (GetBalanceTransactionByOrderRow, error)
	GetChannel(ctx context.Context, arg GetChannelParams) (GetChannelRow, error)
	GetChannelBreakerConfig(ctx context.Context, channelID int64) (GetChannelBreakerConfigRow, error)
	GetChannelHealth(ctx context.Context, channelID int64) (ChannelHealth, error)
	GetChannelHealthForUpdate(ctx context.Context, channelID int64) (ChannelHealth, error)
	GetChannelModel(ctx context.Context, arg GetChannelModelParams) (GetChannelModelRow, error)
	GetChannelSecret(ctx context.Context, arg GetChannelSecretParams) (GetChannelSecretRow, error)
	GetKey(ctx context.Context, arg GetKeyParams) (GetKeyRow, error)
	GetPricing(ctx context.Context, arg GetPricingParams) (GetPricingRow, error)
	GetQuotaPolicy(ctx context.Context, arg GetQuotaPolicyParams) (GetQuotaPolicyRow, error)
	GetRateLimitRule(ctx context.Context, arg GetRateLimitRuleParams) (GetRateLimitRuleRow, error)
	// GetSessionByTokenHash only returns live sessions; an expired token must not
	// authenticate even if its row has not been reaped yet.
	GetSessionByTokenHash(ctx context.Context, tokenHash string) (GetSessionByTokenHashRow, error)
	GetUsageLog(ctx context.Context, arg GetUsageLogParams) (GetUsageLogRow, error)
	GetUser(ctx context.Context, id int64) (GetUserRow, error)
	GetUserBalanceText(ctx context.Context, userID int64) (GetUserBalanceTextRow, error)
	GetUserCredentialsByUsername(ctx context.Context, username pgtype.Text) (GetUserCredentialsByUsernameRow, error)
	InsertUsageLog(ctx context.Context, arg InsertUsageLogParams) (int64, error)
	ListBalanceTransactions(ctx context.Context, arg ListBalanceTransactionsParams) ([]ListBalanceTransactionsRow, error)
	ListCatalogModels(ctx context.Context, arg ListCatalogModelsParams) ([]ListCatalogModelsRow, error)
	ListChannelBreakerConfigs(ctx context.Context, ownerUserID int64) ([]ListChannelBreakerConfigsRow, error)
	ListChannelHealth(ctx context.Context, ownerUserID int64) ([]ChannelHealth, error)
	ListChannelModels(ctx context.Context, arg ListChannelModelsParams) ([]ListChannelModelsRow, error)
	ListChannels(ctx context.Context, ownerUserID int64) ([]ListChannelsRow, error)
	ListKeys(ctx context.Context, arg ListKeysParams) ([]ListKeysRow, error)
	ListPricing(ctx context.Context, ownerUserID int64) ([]ListPricingRow, error)
	ListRateLimitRules(ctx context.Context, arg ListRateLimitRulesParams) ([]ListRateLimitRulesRow, error)
	ListRouteCandidates(ctx context.Context, arg ListRouteCandidatesParams) ([]ListRouteCandidatesRow, error)
	ListUsageLogs(ctx context.Context, arg ListUsageLogsParams) ([]ListUsageLogsRow, error)
	ListUserKeys(ctx context.Context, arg ListUserKeysParams) ([]ListUserKeysRow, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]ListUsersRow, error)
	LockChannel(ctx context.Context, arg LockChannelParams) (int64, error)
	LockUserBalance(ctx context.Context, userID int64) (int64, error)
	StatsChannels(ctx context.Context, arg StatsChannelsParams) ([]StatsChannelsRow, error)
	StatsDaily(ctx context.Context, arg StatsDailyParams) ([]StatsDailyRow, error)
	StatsOverview(ctx context.Context, arg StatsOverviewParams) (StatsOverviewRow, error)
	StatsTTFT(ctx context.Context, arg StatsTTFTParams) (StatsTTFTRow, error)
	SumChannelHealthWindow(ctx context.Context, arg SumChannelHealthWindowParams) (SumChannelHealthWindowRow, error)
	UpdateChannel(ctx context.Context, arg UpdateChannelParams) (int64, error)
	UpdateChannelBalance(ctx context.Context, arg UpdateChannelBalanceParams) (int64, error)
	UpdateChannelHealth(ctx context.Context, arg UpdateChannelHealthParams) (int64, error)
	UpdateChannelModel(ctx context.Context, arg UpdateChannelModelParams) (UpdateChannelModelRow, error)
	UpdateChannelStatus(ctx context.Context, arg UpdateChannelStatusParams) (int64, error)
	UpdateKeyActive(ctx context.Context, arg UpdateKeyActiveParams) (int64, error)
	UpdateKeyLastUsed(ctx context.Context, id int64) (int64, error)
	UpdateKeySecret(ctx context.Context, arg UpdateKeySecretParams) (int64, error)
	UpdateQuotaPolicy(ctx context.Context, arg UpdateQuotaPolicyParams) (int64, error)
	UpdateRateLimitRule(ctx context.Context, arg UpdateRateLimitRuleParams) (int64, error)
	UpdateRateLimitRuleEnabled(ctx context.Context, arg UpdateRateLimitRuleEnabledParams) (int64, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (int64, error)
	UpdateUserBalance(ctx context.Context, arg UpdateUserBalanceParams) (int64, error)
	UpdateUserStatus(ctx context.Context, arg UpdateUserStatusParams) (int64, error)
	UpsertChannelBreakerConfig(ctx context.Context, arg UpsertChannelBreakerConfigParams) error
	UpsertChannelHealthBucket(ctx context.Context, arg UpsertChannelHealthBucketParams) error
	UpsertPricing(ctx context.Context, arg UpsertPricingParams) (int64, error)
}

var _ Querier = (*Queries)(nil)
