// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: rate_limits.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countActiveRateLimitReservations = `-- name: CountActiveRateLimitReservations :one
SELECT count(*) FROM rate_limit_reservations
WHERE status = 'pending' AND expires_at > now()
  AND user_id = $1::bigint
  AND ($2::bigint = 0 OR api_key_id = $2::bigint)
  AND ($3::text = '' OR model = $3::text)
  AND ($4::bigint = 0 OR channel_id = $4::bigint)
`

type CountActiveRateLimitReservationsParams struct {
	UserID    int64  `json:"user_id"`
	ApiKeyID  int64  `json:"api_key_id"`
	Model     string `json:"model"`
	ChannelID int64  `json:"channel_id"`
}

func (q *Queries) CountActiveRateLimitReservations(ctx context.Context, arg CountActiveRateLimitReservationsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveRateLimitReservations,
		arg.UserID,
		arg.ApiKeyID,
		arg.Model,
		arg.ChannelID,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countRateLimitRules = `-- name: CountRateLimitRules :one
SELECT count(*)::int
FROM rate_limit_rules
WHERE owner_user_id = $1
  AND ($2::boolean IS NULL OR enabled = $2::boolean)
`

type CountRateLimitRulesParams struct {
	OwnerUserID int64       `json:"owner_user_id"`
	Enabled     pgtype.Bool `json:"enabled"`
}

func (q *Queries) CountRateLimitRules(ctx context.Context, arg CountRateLimitRulesParams) (int32, error) {
	row := q.db.QueryRow(ctx, countRateLimitRules, arg.OwnerUserID, arg.Enabled)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const createRateLimitRule = `-- name: CreateRateLimitRule :one
INSERT INTO rate_limit_rules (owner_user_id, rule_name, target_type, target_value, metric, limit_value, action, priority, enabled, extras)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10
)
RETURNING id
`

type CreateRateLimitRuleParams struct {
	OwnerUserID int64  `json:"owner_user_id"`
	RuleName    string `json:"rule_name"`
	TargetType  string `json:"target_type"`
	TargetValue string `json:"target_value"`
	Metric      string `json:"metric"`
	LimitValue  int64  `json:"limit_value"`
	Action      string `json:"action"`
	Priority    int32  `json:"priority"`
	Enabled     bool   `json:"enabled"`
	Extras      []byte `json:"extras"`
}

func (q *Queries) CreateRateLimitRule(ctx context.Context, arg CreateRateLimitRuleParams) (int64, error) {
	row := q.db.QueryRow(ctx, createRateLimitRule,
		arg.OwnerUserID,
		arg.RuleName,
		arg.TargetType,
		arg.TargetValue,
		arg.Metric,
		arg.LimitValue,
		arg.Action,
		arg.Priority,
		arg.Enabled,
		arg.Extras,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const deleteRateLimitRule = `-- name: DeleteRateLimitRule :execrows
DELETE FROM rate_limit_rules WHERE id = $1 AND owner_user_id = $2
`

type DeleteRateLimitRuleParams struct {
	ID          int64 `json:"id"`
	OwnerUserID int64 `json:"owner_user_id"`
}

func (q *Queries) DeleteRateLimitRule(ctx context.Context, arg DeleteRateLimitRuleParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteRateLimitRule, arg.ID, arg.OwnerUserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const finalizeRateLimitReservation = `-- name: FinalizeRateLimitReservation :execrows
UPDATE rate_limit_reservations SET status = 'settled' WHERE id = $1 AND status = 'pending'
`

func (q *Queries) FinalizeRateLimitReservation(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, finalizeRateLimitReservation, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getRateLimitRule = `-- name: GetRateLimitRule :one
SELECT id, rule_name, target_type, target_value, metric, limit_value, action, priority, enabled, extras
FROM rate_limit_rules
WHERE id = $1 AND owner_user_id = $2
`

type GetRateLimitRuleParams struct {
	ID          int64 `json:"id"`
	OwnerUserID int64 `json:"owner_user_id"`
}

type GetRateLimitRuleRow struct {
	ID          int64  `json:"id"`
	RuleName    string `json:"rule_name"`
	TargetType  string `json:"target_type"`
	TargetValue string `json:"target_value"`
	Metric      string `json:"metric"`
	LimitValue  int64  `json:"limit_value"`
	Action      string `json:"action"`
	Priority    int32  `json:"priority"`
	Enabled     bool   `json:"enabled"`
	Extras      []byte `json:"extras"`
}

func (q *Queries) GetRateLimitRule(ctx context.Context, arg GetRateLimitRuleParams) (GetRateLimitRuleRow, error) {
	row := q.db.QueryRow(ctx, getRateLimitRule, arg.ID, arg.OwnerUserID)
	var i GetRateLimitRuleRow
	err := row.Scan(
		&i.ID,
		&i.RuleName,
		&i.TargetType,
		&i.TargetValue,
		&i.Metric,
		&i.LimitValue,
		&i.Action,
		&i.Priority,
		&i.Enabled,
		&i.Extras,
	)
	return i, err
}

const insertRateLimitReservation = `-- name: InsertRateLimitReservation :one
INSERT INTO rate_limit_reservations (request_id, user_id, api_key_id, model, channel_id, estimated_tokens, expires_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id
`

type InsertRateLimitReservationParams struct {
	RequestID       string             `json:"request_id"`
	UserID          int64              `json:"user_id"`
	ApiKeyID        int64              `json:"api_key_id"`
	Model           string             `json:"model"`
	ChannelID       pgtype.Int8        `json:"channel_id"`
	EstimatedTokens int64              `json:"estimated_tokens"`
	ExpiresAt       pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) InsertRateLimitReservation(ctx context.Context, arg InsertRateLimitReservationParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertRateLimitReservation,
		arg.RequestID,
		arg.UserID,
		arg.ApiKeyID,
		arg.Model,
		arg.ChannelID,
		arg.EstimatedTokens,
		arg.ExpiresAt,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const listRateLimitRules = `-- name: ListRateLimitRules :many
SELECT id, rule_name, target_type, target_value, metric, limit_value, action, priority, enabled, extras
FROM rate_limit_rules
WHERE owner_user_id = $1
  AND ($2::boolean IS NULL OR enabled = $2::boolean)
ORDER BY priority, id
LIMIT $4 OFFSET $3
`

type ListRateLimitRulesParams struct {
	OwnerUserID int64       `json:"owner_user_id"`
	Enabled     pgtype.Bool `json:"enabled"`
	PageOffset  int32       `json:"page_offset"`
	PageLimit   int32       `json:"page_limit"`
}

type ListRateLimitRulesRow struct {
	ID          int64  `json:"id"`
	RuleName    string `json:"rule_name"`
	TargetType  string `json:"target_type"`
	TargetValue string `json:"target_value"`
	Metric      string `json:"metric"`
	LimitValue  int64  `json:"limit_value"`
	Action      string `json:"action"`
	Priority    int32  `json:"priority"`
	Enabled     bool   `json:"enabled"`
	Extras      []byte `json:"extras"`
}

func (q *Queries) ListRateLimitRules(ctx context.Context, arg ListRateLimitRulesParams) ([]ListRateLimitRulesRow, error) {
	rows, err := q.db.Query(ctx, listRateLimitRules,
		arg.OwnerUserID,
		arg.Enabled,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRateLimitRulesRow{}
	for rows.Next() {
		var i ListRateLimitRulesRow
		if err := rows.Scan(
			&i.ID,
			&i.RuleName,
			&i.TargetType,
			&i.TargetValue,
			&i.Metric,
			&i.LimitValue,
			&i.Action,
			&i.Priority,
			&i.Enabled,
			&i.Extras,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rateLimitAPIKeyOwnedByUser = `-- name: RateLimitAPIKeyOwnedByUser :one
SELECT EXISTS (SELECT 1 FROM client_api_keys WHERE id = $1::bigint AND user_id = $2::bigint)
`

type RateLimitAPIKeyOwnedByUserParams struct {
	ID          int64 `json:"id"`
	OwnerUserID int64 `json:"owner_user_id"`
}

func (q *Queries) RateLimitAPIKeyOwnedByUser(ctx context.Context, arg RateLimitAPIKeyOwnedByUserParams) (bool, error) {
	row := q.db.QueryRow(ctx, rateLimitAPIKeyOwnedByUser, arg.ID, arg.OwnerUserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const rateLimitChannelOwnedByUser = `-- name: RateLimitChannelOwnedByUser :one
SELECT EXISTS (SELECT 1 FROM channels WHERE id = $1::bigint AND owner_user_id = $2::bigint)
`

type RateLimitChannelOwnedByUserParams struct {
	ID          int64 `json:"id"`
	OwnerUserID int64 `json:"owner_user_id"`
}

func (q *Queries) RateLimitChannelOwnedByUser(ctx context.Context, arg RateLimitChannelOwnedByUserParams) (bool, error) {
	row := q.db.QueryRow(ctx, rateLimitChannelOwnedByUser, arg.ID, arg.OwnerUserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const rateLimitModelOwnedByUser = `-- name: RateLimitModelOwnedByUser :one
SELECT EXISTS (
    SELECT 1 FROM channel_models cm
    JOIN channels c ON c.id = cm.channel_id
    WHERE cm.model_name = $1::text AND c.owner_user_id = $2::bigint
)
`

type RateLimitModelOwnedByUserParams struct {
	ModelName   string `json:"model_name"`
	OwnerUserID int64  `json:"owner_user_id"`
}

func (q *Queries) RateLimitModelOwnedByUser(ctx context.Context, arg RateLimitModelOwnedByUserParams) (bool, error) {
	row := q.db.QueryRow(ctx, rateLimitModelOwnedByUser, arg.ModelName, arg.OwnerUserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const reapRateLimitReservations = `-- name: ReapRateLimitReservations :execrows
WITH expired AS (
    SELECT id FROM rate_limit_reservations
    WHERE status = 'pending' AND expires_at <= now()
    ORDER BY id LIMIT $1::integer
)
UPDATE rate_limit_reservations SET status = 'expired' WHERE id IN (SELECT id FROM expired)
`

func (q *Queries) ReapRateLimitReservations(ctx context.Context, batchLimit int32) (int64, error) {
	result, err := q.db.Exec(ctx, reapRateLimitReservations, batchLimit)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const releaseRateLimitReservation = `-- name: ReleaseRateLimitReservation :execrows
UPDATE rate_limit_reservations SET status = 'released', released_at = now() WHERE id = $1 AND status = 'pending'
`

func (q *Queries) ReleaseRateLimitReservation(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, releaseRateLimitReservation, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateRateLimitRuleEnabled = `-- name: UpdateRateLimitRuleEnabled :execrows
UPDATE rate_limit_rules
SET enabled = $1, updated_at = now()
WHERE id = $2 AND owner_user_id = $3
`

type UpdateRateLimitRuleEnabledParams struct {
	Enabled     bool  `json:"enabled"`
	ID          int64 `json:"id"`
	OwnerUserID int64 `json:"owner_user_id"`
}

func (q *Queries) UpdateRateLimitRuleEnabled(ctx context.Context, arg UpdateRateLimitRuleEnabledParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateRateLimitRuleEnabled, arg.Enabled, arg.ID, arg.OwnerUserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
