// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countUserKeys = `-- name: CountUserKeys :one
SELECT count(*)::int FROM client_api_keys WHERE user_id = $1
`

func (q *Queries) CountUserKeys(ctx context.Context, userID int64) (int32, error) {
	row := q.db.QueryRow(ctx, countUserKeys, userID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const createKey = `-- name: CreateKey :one
INSERT INTO client_api_keys (user_id, key_name, prefix, key_hash, key_suffix, permissions, rate_limit_overrides, expires_at, is_active)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    NULLIF($8, '')::timestamptz,
    $9
)
RETURNING id
`

type CreateKeyParams struct {
	UserID             int64       `json:"user_id"`
	KeyName            string      `json:"key_name"`
	Prefix             string      `json:"prefix"`
	KeyHash            string      `json:"key_hash"`
	KeySuffix          string      `json:"key_suffix"`
	Permissions        []byte      `json:"permissions"`
	RateLimitOverrides []byte      `json:"rate_limit_overrides"`
	ExpiresAt          interface{} `json:"expires_at"`
	IsActive           bool        `json:"is_active"`
}

func (q *Queries) CreateKey(ctx context.Context, arg CreateKeyParams) (int64, error) {
	row := q.db.QueryRow(ctx, createKey,
		arg.UserID,
		arg.KeyName,
		arg.Prefix,
		arg.KeyHash,
		arg.KeySuffix,
		arg.Permissions,
		arg.RateLimitOverrides,
		arg.ExpiresAt,
		arg.IsActive,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (token_hash, user_id, expires_at)
VALUES ($1, $2, $3)
RETURNING id
`

type CreateSessionParams struct {
	TokenHash string             `json:"token_hash"`
	UserID    int64              `json:"user_id"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (int64, error) {
	row := q.db.QueryRow(ctx, createSession, arg.TokenHash, arg.UserID, arg.ExpiresAt)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const createUserWithCredentials = `-- name: CreateUserWithCredentials :one
INSERT INTO users (username, nickname, password_hash)
VALUES ($1, $2, $3)
RETURNING id
`

type CreateUserWithCredentialsParams struct {
	Username     string `json:"username"`
	Nickname     string `json:"nickname"`
	PasswordHash string `json:"password_hash"`
}

func (q *Queries) CreateUserWithCredentials(ctx context.Context, arg CreateUserWithCredentialsParams) (int64, error) {
	row := q.db.QueryRow(ctx, createUserWithCredentials, arg.Username, arg.Nickname, arg.PasswordHash)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :execrows
DELETE FROM sessions
WHERE id IN (
    SELECT id FROM sessions WHERE expires_at <= now() ORDER BY id LIMIT $1
)
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context, maxRows int32) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredSessions, maxRows)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteKey = `-- name: DeleteKey :execrows
DELETE FROM client_api_keys WHERE id = $1 AND user_id = $2
`

type DeleteKeyParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) DeleteKey(ctx context.Context, arg DeleteKeyParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteKey, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteSessionByTokenHash = `-- name: DeleteSessionByTokenHash :execrows
DELETE FROM sessions WHERE token_hash = $1
`

func (q *Queries) DeleteSessionByTokenHash(ctx context.Context, tokenHash string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteSessionByTokenHash, tokenHash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getAccountByID = `-- name: GetAccountByID :one
SELECT id, username, nickname
FROM users
WHERE id = $1
`

type GetAccountByIDRow struct {
	ID       int64  `json:"id"`
	Username string `json:"username"`
	Nickname string `json:"nickname"`
}

func (q *Queries) GetAccountByID(ctx context.Context, id int64) (GetAccountByIDRow, error) {
	row := q.db.QueryRow(ctx, getAccountByID, id)
	var i GetAccountByIDRow
	err := row.Scan(&i.ID, &i.Username, &i.Nickname)
	return i, err
}

const getAuthContextByKeyHash = `-- name: GetAuthContextByKeyHash :one
SELECT
    k.id AS key_id,
    k.user_id,
    k.key_name,
    k.is_active AS key_active,
    k.expires_at,
    k.permissions,
    k.rate_limit_overrides
FROM client_api_keys k
WHERE k.key_hash = $1
`

type GetAuthContextByKeyHashRow struct {
	KeyID              int64              `json:"key_id"`
	UserID             int64              `json:"user_id"`
	KeyName            string             `json:"key_name"`
	KeyActive          bool               `json:"key_active"`
	ExpiresAt          pgtype.Timestamptz `json:"expires_at"`
	Permissions        []byte             `json:"permissions"`
	RateLimitOverrides []byte             `json:"rate_limit_overrides"`
}

func (q *Queries) GetAuthContextByKeyHash(ctx context.Context, keyHash string) (GetAuthContextByKeyHashRow, error) {
	row := q.db.QueryRow(ctx, getAuthContextByKeyHash, keyHash)
	var i GetAuthContextByKeyHashRow
	err := row.Scan(
		&i.KeyID,
		&i.UserID,
		&i.KeyName,
		&i.KeyActive,
		&i.ExpiresAt,
		&i.Permissions,
		&i.RateLimitOverrides,
	)
	return i, err
}

const getKey = `-- name: GetKey :one
SELECT id, user_id, key_name, prefix, key_suffix, is_active, created_at, last_used_at, expires_at
FROM client_api_keys
WHERE id = $1 AND user_id = $2
`

type GetKeyParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

type GetKeyRow struct {
	ID         int64              `json:"id"`
	UserID     int64              `json:"user_id"`
	KeyName    string             `json:"key_name"`
	Prefix     string             `json:"prefix"`
	KeySuffix  string             `json:"key_suffix"`
	IsActive   bool               `json:"is_active"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	LastUsedAt pgtype.Timestamptz `json:"last_used_at"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) GetKey(ctx context.Context, arg GetKeyParams) (GetKeyRow, error) {
	row := q.db.QueryRow(ctx, getKey, arg.ID, arg.UserID)
	var i GetKeyRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.KeyName,
		&i.Prefix,
		&i.KeySuffix,
		&i.IsActive,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const getSessionByTokenHash = `-- name: GetSessionByTokenHash :one
SELECT id, token_hash, user_id, expires_at
FROM sessions
WHERE token_hash = $1 AND expires_at > now()
`

type GetSessionByTokenHashRow struct {
	ID        int64              `json:"id"`
	TokenHash string             `json:"token_hash"`
	UserID    int64              `json:"user_id"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

// GetSessionByTokenHash only returns live sessions; an expired token must not
// authenticate even if its row has not been reaped yet.
func (q *Queries) GetSessionByTokenHash(ctx context.Context, tokenHash string) (GetSessionByTokenHashRow, error) {
	row := q.db.QueryRow(ctx, getSessionByTokenHash, tokenHash)
	var i GetSessionByTokenHashRow
	err := row.Scan(
		&i.ID,
		&i.TokenHash,
		&i.UserID,
		&i.ExpiresAt,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT id, username, nickname
FROM users
WHERE id = $1
`

type GetUserRow struct {
	ID       int64  `json:"id"`
	Username string `json:"username"`
	Nickname string `json:"nickname"`
}

func (q *Queries) GetUser(ctx context.Context, id int64) (GetUserRow, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i GetUserRow
	err := row.Scan(&i.ID, &i.Username, &i.Nickname)
	return i, err
}

const getUserCredentialsByID = `-- name: GetUserCredentialsByID :one
SELECT id, username, nickname, password_hash
FROM users
WHERE id = $1
`

type GetUserCredentialsByIDRow struct {
	ID           int64  `json:"id"`
	Username     string `json:"username"`
	Nickname     string `json:"nickname"`
	PasswordHash string `json:"password_hash"`
}

func (q *Queries) GetUserCredentialsByID(ctx context.Context, id int64) (GetUserCredentialsByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserCredentialsByID, id)
	var i GetUserCredentialsByIDRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Nickname,
		&i.PasswordHash,
	)
	return i, err
}

const getUserCredentialsByUsername = `-- name: GetUserCredentialsByUsername :one
SELECT id, username, nickname, password_hash
FROM users
WHERE username = $1
`

type GetUserCredentialsByUsernameRow struct {
	ID           int64  `json:"id"`
	Username     string `json:"username"`
	Nickname     string `json:"nickname"`
	PasswordHash string `json:"password_hash"`
}

func (q *Queries) GetUserCredentialsByUsername(ctx context.Context, username string) (GetUserCredentialsByUsernameRow, error) {
	row := q.db.QueryRow(ctx, getUserCredentialsByUsername, username)
	var i GetUserCredentialsByUsernameRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Nickname,
		&i.PasswordHash,
	)
	return i, err
}

const listUserKeys = `-- name: ListUserKeys :many
SELECT id, user_id, key_name, prefix, key_suffix, is_active, created_at, last_used_at, expires_at
FROM client_api_keys
WHERE user_id = $1
ORDER BY id
LIMIT $2 OFFSET $3
`

type ListUserKeysParams struct {
	UserID int64 `json:"user_id"`
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListUserKeysRow struct {
	ID         int64              `json:"id"`
	UserID     int64              `json:"user_id"`
	KeyName    string             `json:"key_name"`
	Prefix     string             `json:"prefix"`
	KeySuffix  string             `json:"key_suffix"`
	IsActive   bool               `json:"is_active"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	LastUsedAt pgtype.Timestamptz `json:"last_used_at"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) ListUserKeys(ctx context.Context, arg ListUserKeysParams) ([]ListUserKeysRow, error) {
	rows, err := q.db.Query(ctx, listUserKeys, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUserKeysRow{}
	for rows.Next() {
		var i ListUserKeysRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.KeyName,
			&i.Prefix,
			&i.KeySuffix,
			&i.IsActive,
			&i.CreatedAt,
			&i.LastUsedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateKeyActive = `-- name: UpdateKeyActive :execrows
UPDATE client_api_keys
SET is_active = $1, updated_at = now()
WHERE id = $2 AND user_id = $3
`

type UpdateKeyActiveParams struct {
	IsActive bool  `json:"is_active"`
	ID       int64 `json:"id"`
	UserID   int64 `json:"user_id"`
}

func (q *Queries) UpdateKeyActive(ctx context.Context, arg UpdateKeyActiveParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateKeyActive, arg.IsActive, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateKeyLastUsed = `-- name: UpdateKeyLastUsed :execrows
UPDATE client_api_keys
SET last_used_at = now(), updated_at = now()
WHERE id = $1
`

func (q *Queries) UpdateKeyLastUsed(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, updateKeyLastUsed, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateUserPassword = `-- name: UpdateUserPassword :execrows
UPDATE users
SET password_hash = $1, updated_at = now()
WHERE id = $2
`

type UpdateUserPasswordParams struct {
	PasswordHash string `json:"password_hash"`
	ID           int64  `json:"id"`
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateUserPassword, arg.PasswordHash, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateUserProfile = `-- name: UpdateUserProfile :execrows
UPDATE users
SET nickname = $1, updated_at = now()
WHERE id = $2
`

type UpdateUserProfileParams struct {
	Nickname string `json:"nickname"`
	ID       int64  `json:"id"`
}

func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateUserProfile, arg.Nickname, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
