import { fireEvent, screen, waitFor, within } from '@testing-library/react'
import userEvent from '@testing-library/user-event'
import { expect, it, vi } from 'vitest'
import { ChannelsPage } from '../src/pages/ChannelsPage'
import { channel, fail, health, list, mapping, renderPage, requests, respond } from './support'

it('creates and edits channels, reports failed actions, switches status, resets health, and confirms deletion', async () => {
  const user = userEvent.setup(); const confirm = vi.spyOn(window, 'confirm').mockReturnValue(true)
  renderPage(<ChannelsPage />)
  await screen.findByText('Primary')
  await user.click(screen.getByRole('button', { name: '刷新' }))
  await user.click(screen.getByRole('button', { name: '新建渠道' }))
  await user.type(screen.getByLabelText('渠道名称'), 'New'); await user.type(screen.getByLabelText('Base URL'), 'https://new.example/v1')
  fireEvent.submit(screen.getByRole('dialog'))
  expect(await screen.findByRole('alert')).toHaveTextContent('新建渠道必须填写上游 API Key')
  await user.type(screen.getByLabelText('上游 API Key'), 'test-placeholder')
  await user.type(screen.getByLabelText('余额'), '1.000000')
  await user.click(screen.getByRole('button', { name: '创建' }))
  await waitFor(() => expect(screen.queryByRole('dialog')).not.toBeInTheDocument())
  expect(requests.find(r => r.method === 'POST' && r.path === '/admin/channels')?.body).toMatchObject({ name: 'New', api_key: 'test-placeholder', balance: '1.000000' })
  await user.click(screen.getByRole('button', { name: '编辑' }))
  await user.clear(screen.getByLabelText('渠道名称')); await user.type(screen.getByLabelText('渠道名称'), 'Edited')
  await user.click(screen.getByRole('button', { name: '保存' }))
  await waitFor(() => expect(screen.queryByRole('dialog')).not.toBeInTheDocument())
  expect(requests.find(r => r.method === 'PUT' && r.path === '/admin/channels/2')?.body).toMatchObject({ name: 'Edited' })
  respond('/admin/channels/2/status', fail('toggle failed'), 'PUT')
  await user.click(screen.getByRole('button', { name: '切换状态' })); await screen.findByText('toggle failed')
  respond('/admin/channels/2/status', channel, 'PUT')
  await user.click(screen.getByRole('button', { name: '切换状态' }))
  await user.click(screen.getByRole('button', { name: '解除熔断' }))
  confirm.mockReturnValueOnce(false); await user.click(screen.getByRole('button', { name: '删除' }))
  expect(requests.some(r => r.method === 'DELETE' && r.path === '/admin/channels/2')).toBe(false)
  respond('/admin/channels', list([])); await user.click(screen.getByRole('button', { name: '删除' }))
  await screen.findByText('暂无渠道')
  await user.click(screen.getByRole('button', { name: '新建渠道' })); await user.click(screen.getByRole('button', { name: '取消' }))
})

it('loads and saves user breaker configuration and restores process defaults', async () => {
  const user = userEvent.setup()
  renderPage(<ChannelsPage />)
  await screen.findByText('Primary')
  await user.click(screen.getByRole('button', { name: '用户熔断配置' }))
  await screen.findByLabelText('统计窗口（秒）')
  await user.clear(screen.getByLabelText('统计窗口（秒）')); await user.type(screen.getByLabelText('统计窗口（秒）'), '90')
  await user.click(screen.getByRole('button', { name: '保存' }))
  await waitFor(() => expect(screen.queryByRole('dialog')).not.toBeInTheDocument())
  expect(requests.find(r => r.method === 'PUT' && r.path === '/admin/breaker-config')?.body).toMatchObject({ window_seconds: 90 })
  await user.click(screen.getByRole('button', { name: '用户熔断配置' })); await screen.findByLabelText('统计窗口（秒）')
  await user.click(screen.getByRole('button', { name: '恢复进程默认' }))
  await waitFor(() => expect(screen.queryByRole('dialog')).not.toBeInTheDocument())
  expect(requests.some(r => r.method === 'DELETE' && r.path === '/admin/breaker-config')).toBe(true)
  await user.click(screen.getByRole('button', { name: '用户熔断配置' })); await user.click(screen.getByRole('button', { name: '取消' }))
})

it('tests all/single upstream models, displays failures and empty results, and closes', async () => {
  const user = userEvent.setup()
  renderPage(<ChannelsPage />); await screen.findByText('Primary')
  respond('/admin/channels/2/test', fail('probe offline'), 'POST')
  await user.click(screen.getByRole('button', { name: '测试', exact: true }))
  await screen.findByText('probe offline')
  respond('/admin/channels/2/test', { list: [{ model_alias: 'gpt', upstream_model: 'gpt-real', http_status: 200, latency_ms: 5, ok: true, error: '' }, { model_alias: 'bad', upstream_model: 'bad-real', http_status: 503, latency_ms: 6, ok: false, error: 'upstream unavailable' }] }, 'POST')
  await user.click(screen.getByRole('button', { name: '测试全部模型' })); await screen.findByText('upstream unavailable')
  respond('/admin/channels/2/test', { list: [] }, 'POST')
  await user.click(screen.getByRole('button', { name: '测试单个模型' })); await screen.findByText('暂无模型映射可测试')
  expect(requests.filter(r => r.path === '/admin/channels/2/test').at(-1)?.body).toEqual({ check_all: false })
  await user.click(screen.getByRole('button', { name: '取消' }))
})

it('loads remote models, maps individually/all, catches mapping errors, and edits/deletes manual mappings', async () => {
  const user = userEvent.setup(); vi.spyOn(window, 'confirm').mockReturnValue(true)
  renderPage(<ChannelsPage />); await screen.findByText('Primary')
  await user.click(screen.getByRole('button', { name: '模型映射' }))
  await screen.findByText('gpt-real')
  respond('/admin/channels/2/remote-models', { ok: false, error: 'remote unavailable' }, 'POST')
  await user.click(screen.getByRole('button', { name: '拉取远端模型' })); await screen.findByText('remote unavailable')
  respond('/admin/channels/2/remote-models', { ok: true, models: [{ id: 'gpt-new' }, { id: 'gpt-other' }] }, 'POST')
  await user.click(screen.getByRole('button', { name: '拉取远端模型' })); await screen.findByText('gpt-new')
  respond('/admin/channels/2/models', fail('mapping unavailable'), 'POST')
  await user.click(screen.getByRole('button', { name: /gpt-new：gpt-new/ })); await screen.findByText('mapping unavailable')
  respond('/admin/channels/2/models', mapping, 'POST')
  await user.click(screen.getByRole('button', { name: '一键全部映射' }))
  await waitFor(() => expect(requests.filter(r => r.method === 'POST' && r.path === '/admin/channels/2/models')).toHaveLength(3))
  await user.click(screen.getByRole('button', { name: '手动添加映射' }))
  await user.type(screen.getByLabelText('对外模型名'), 'gpt'); await user.type(screen.getByLabelText('上游模型名'), 'gpt-real')
  await user.click(screen.getByRole('button', { name: '保存' })); await screen.findByText('同一渠道已存在该对外模型名')
  await user.clear(screen.getByLabelText('对外模型名')); await user.type(screen.getByLabelText('对外模型名'), 'new-alias')
  await user.click(screen.getByRole('button', { name: '保存' }))
  await waitFor(() => expect(screen.getAllByRole('dialog')).toHaveLength(1))
  await user.click(within(screen.getByRole('dialog')).getByRole('button', { name: '编辑' }))
  await user.clear(screen.getByLabelText('对外模型名')); await user.type(screen.getByLabelText('对外模型名'), 'edited-alias')
  await user.click(screen.getByRole('button', { name: '保存' }))
  await waitFor(() => expect(screen.getAllByRole('dialog')).toHaveLength(1))
  expect(requests.find(r => r.method === 'PUT' && r.path === '/admin/channels/2/models/3')?.body).toEqual({ model_name: 'edited-alias', enabled: true })
  await user.click(within(screen.getByRole('dialog')).getByRole('button', { name: '删除' }))
  await waitFor(() => expect(requests.some(r => r.method === 'DELETE' && r.path === '/admin/channels/2/models/3')).toBe(true))
  await user.click(screen.getByRole('button', { name: '手动添加映射' }))
  await user.click(within(screen.getAllByRole('dialog')[1]).getByRole('button', { name: '取消' }))
  await user.click(screen.getByRole('button', { name: '取消' }))
})

it('retries a failed channel/health load', async () => {
  respond('/admin/channels', fail('offline')); respond('/admin/channels/health', fail('offline'))
  renderPage(<ChannelsPage />)
  await screen.findByText(/该面板暂时无法加载/)
  respond('/admin/channels', list([channel])); respond('/admin/channels/health', list([health]))
  await userEvent.click(screen.getByRole('button', { name: '重试' })); await screen.findByText('Primary')
})

it('skips blank remote IDs and rejects edits that collide with an existing public model', async () => {
  const user = userEvent.setup()
  respond('/admin/channels/2/models', list([mapping, { ...mapping, id: 9, model_name: 'existing' }]))
  respond('/admin/channels/2/remote-models', { ok: true, models: [{ id: '' }] }, 'POST')
  renderPage(<ChannelsPage />); await screen.findByText('Primary')
  await user.click(screen.getByRole('button', { name: '模型映射' }))
  await screen.findByText('existing')
  await user.click(screen.getByRole('button', { name: '拉取远端模型' }))
  await waitFor(() => expect(screen.getByRole('button', { name: '一键全部映射' })).not.toBeDisabled())
  await user.click(screen.getByRole('button', { name: '一键全部映射' }))
  expect(requests.some(r => r.method === 'POST' && r.path === '/admin/channels/2/models')).toBe(false)
  await user.click(within(screen.getByRole('dialog')).getAllByRole('button', { name: '编辑' })[0])
  await user.clear(screen.getByLabelText('对外模型名')); await user.type(screen.getByLabelText('对外模型名'), 'existing')
  await user.click(screen.getByRole('button', { name: '保存' }))
  await screen.findByText('同一渠道已存在该对外模型名')
  expect(requests.some(r => r.method === 'PUT' && r.path === '/admin/channels/2/models/3')).toBe(false)
})
