import { fireEvent, screen, waitFor, within } from '@testing-library/react'
import userEvent from '@testing-library/user-event'
import { expect, it } from 'vitest'
import { LimitsPage, PricingPage, QuotasPage } from '../src/pages/ConsolePages'
import { channel, fail, key, list, mapping, policy, quotaUsage, renderPage, requests, respond, rule } from './support'

it('renders all rule targets, validates integer limits, changes targets, and creates/toggles/deletes', async () => {
  const user = userEvent.setup()
  respond('/admin/rate-limits', list(['user', 'api_key', 'model', 'channel', 'legacy'].map((target_type, index) => ({ ...rule, id: index + 1, rule_name: `rule-${target_type}`, target_type, target_value: target_type === 'api_key' ? '11' : target_type === 'channel' ? '2' : 'gpt', metric: index === 4 ? 'concurrency' : 'rpm' }))))
  renderPage(<LimitsPage />)
  await screen.findByText('rule-channel')
  expect(screen.getByText('密钥 production')).toBeInTheDocument(); expect(screen.getByText('渠道 Primary')).toBeInTheDocument()
  await user.click(screen.getByRole('button', { name: '刷新' }))
  await user.click(screen.getByRole('button', { name: '新建' }))
  await user.type(screen.getByLabelText('规则名'), 'new-rule')
  await user.type(screen.getByLabelText('限额'), 'nope')
  await user.click(screen.getByRole('button', { name: '创建' }))
  expect(await screen.findByRole('alert')).toHaveTextContent('请输入正整数')
  await user.clear(screen.getByLabelText('限额')); await user.type(screen.getByLabelText('限额'), '0')
  await user.click(screen.getByRole('button', { name: '创建' }))
  expect(await screen.findByRole('alert')).toHaveTextContent('须为 1 到')
  for (const type of ['api_key', 'model', 'channel', 'user']) {
    await user.selectOptions(screen.getByLabelText('作用域'), type)
    if (type !== 'user') await user.selectOptions(screen.getByLabelText('目标值'), '*')
  }
  await user.clear(screen.getByLabelText('限额')); await user.type(screen.getByLabelText('限额'), '1,000')
  await user.click(screen.getByRole('button', { name: '创建' }))
  await waitFor(() => expect(screen.queryByRole('dialog')).not.toBeInTheDocument())
  expect(requests.find(r => r.method === 'POST' && r.path === '/admin/rate-limits')?.body).toMatchObject({ target_type: 'user', target_value: '*', limit_value: 1000 })
  await user.click(screen.getAllByRole('button', { name: '切换' })[0])
  await waitFor(() => expect(requests.some(r => r.method === 'PUT' && r.path === '/admin/rate-limits/1')).toBe(true))
  await user.click(screen.getAllByRole('button', { name: '删除' })[0])
  await waitFor(() => expect(requests.some(r => r.method === 'DELETE' && r.path === '/admin/rate-limits/1')).toBe(true))
  await user.click(screen.getByRole('button', { name: '新建' })); await user.click(screen.getByRole('button', { name: '取消' }))
})

it('matches quota buckets to policies without showing reservations, and creates each optional-limit variant', async () => {
  const user = userEvent.setup()
  respond('/admin/quota-policies', list([policy, { ...policy, id: 8, policy_name: 'monthly', scope_type: 'api_key', scope_id: 11, period_type: 'month', token_limit: null, cost_limit: null, enabled: false }]))
  respond('/admin/quota-usage', list([{ ...quotaUsage, used_cost: '9007199254740993.123456' }]))
  renderPage(<QuotasPage />, true)
  await screen.findByText('daily cap'); await screen.findByText('密钥 production')
  expect(screen.getByText('9007199254740993.123456')).toBeInTheDocument()
  expect(screen.queryByText('999')).not.toBeInTheDocument(); expect(screen.queryByText('888.000000')).not.toBeInTheDocument()
  await user.click(screen.getByRole('button', { name: '刷新' }))
  await user.click(screen.getByRole('button', { name: '新建' }))
  await user.type(screen.getByLabelText('策略名'), 'new-policy')
  await user.click(screen.getByRole('button', { name: '创建' }))
  expect(await screen.findByRole('alert')).toHaveTextContent('至少填写一项')
  await user.type(screen.getByLabelText('Token 限额（可选）'), '2，000')
  await user.type(screen.getByLabelText('费用限额（可选）'), '1.000000')
  await user.selectOptions(screen.getByLabelText('作用域'), 'api_key')
  await user.selectOptions(screen.getByLabelText('作用域对象'), '11')
  await user.selectOptions(screen.getByLabelText('作用域'), 'user')
  await user.click(screen.getByRole('button', { name: '创建' }))
  await waitFor(() => expect(screen.queryByRole('dialog')).not.toBeInTheDocument())
  expect(requests.filter(r => r.method === 'POST' && r.path === '/admin/quota-policies').at(-1)?.body).toMatchObject({ scope_id: 1, token_limit: 2000, cost_limit: '1.000000' })
  await user.click(screen.getByRole('button', { name: '新建' })); await user.type(screen.getByLabelText('策略名'), 'cost-only')
  await user.type(screen.getByLabelText('费用限额（可选）'), '2.000000')
  await user.click(screen.getByRole('button', { name: '创建' }))
  await waitFor(() => expect(screen.queryByRole('dialog')).not.toBeInTheDocument())
  expect(requests.filter(r => r.method === 'POST' && r.path === '/admin/quota-policies').at(-1)?.body).not.toHaveProperty('token_limit')
  respond('/admin/quota-policies/6', fail('quota delete failed'), 'DELETE')
  await user.click(screen.getAllByRole('button', { name: '删除' })[0]); await screen.findByText('quota delete failed')
  respond('/admin/quota-policies/6', { deleted: true }, 'DELETE')
  await user.click(screen.getAllByRole('button', { name: '删除' })[0])
  await waitFor(() => expect(requests.filter(r => r.method === 'DELETE').length).toBe(2))
  await user.click(screen.getByRole('button', { name: '新建' })); await user.click(screen.getByRole('button', { name: '取消' }))
})

it('reports quota loading failure and validates missing session/key scope', async () => {
  const user = userEvent.setup()
  respond('/admin/auth/me', fail('missing', 401)); respond('/admin/keys', list([]))
  respond('/admin/quota-usage', fail('bucket unavailable'))
  renderPage(<QuotasPage />, true)
  expect(screen.getByText('加载中…')).toBeInTheDocument()
  await screen.findByRole('alert')
  expect(screen.getByRole('alert')).toHaveTextContent('bucket unavailable')
  await user.click(screen.getByRole('button', { name: '新建' })); await user.type(screen.getByLabelText('策略名'), 'cap')
  await user.type(screen.getByLabelText('Token 限额（可选）'), '100')
  await user.click(screen.getByRole('button', { name: '创建' }))
  expect(await screen.findByText('当前用户信息缺失')).toBeInTheDocument()
  await user.selectOptions(screen.getByLabelText('作用域'), 'api_key')
  await user.click(screen.getByRole('button', { name: '创建' }))
  expect(await screen.findByText('请选择密钥')).toBeInTheDocument()
})

it('creates pricing from a channel mapping, changes selectors, and preserves JSON DELETE', async () => {
  const user = userEvent.setup()
  respond('/admin/channels', list([channel, { ...channel, id: 9, name: 'Secondary' }]))
  respond('/admin/channels/9/models', list([{ ...mapping, upstream_model: 'model-nine' }, { ...mapping, id: 8, upstream_model: 'model-eight' }]))
  renderPage(<PricingPage />)
  await screen.findByText('gpt-real')
  await user.click(screen.getByRole('button', { name: '刷新' }))
  await user.click(screen.getByRole('button', { name: '新建' }))
  await user.selectOptions(screen.getByLabelText('渠道'), '9')
  await screen.findByRole('option', { name: 'model-eight' })
  await user.selectOptions(screen.getByLabelText('上游模型'), 'model-eight')
  await user.type(screen.getByLabelText('输入单价 / 1M'), '0.123456'); await user.type(screen.getByLabelText('输出单价 / 1M'), '1.000000')
  await user.type(screen.getByLabelText('缓存输入单价 / 1M（可选）'), '0.010000')
  await user.click(screen.getByRole('button', { name: '创建' }))
  await waitFor(() => expect(screen.queryByRole('dialog')).not.toBeInTheDocument())
  expect(requests.find(r => r.method === 'POST' && r.path === '/admin/pricing')?.body).toMatchObject({ channel_id: 9, upstream_model: 'model-eight', cached_input_price_per_1m: '0.010000' })
  await user.click(screen.getByRole('button', { name: '删除' }))
  await waitFor(() => expect(requests.some(r => r.method === 'DELETE' && r.path === '/admin/pricing')).toBe(true))
  expect(requests.find(r => r.method === 'DELETE' && r.path === '/admin/pricing')?.body).toEqual({ channel_id: 2, upstream_model: 'gpt-real' })
  await user.click(screen.getByRole('button', { name: '新建' })); await user.click(screen.getByRole('button', { name: '取消' }))
})

it.each(['channels', 'mappings'])('rejects pricing without %s', async kind => {
  respond('/admin/pricing', list([]))
  if (kind === 'channels') respond('/admin/channels', list([]))
  else respond('/admin/channels/2/models', list([]))
  renderPage(<PricingPage />)
  await waitFor(() => expect(requests.some(r => r.path === '/admin/channels')).toBe(true))
  await userEvent.click(screen.getByRole('button', { name: '新建' }))
  const dialog = screen.getByRole('dialog')
  await userEvent.type(screen.getByLabelText('输入单价 / 1M'), '1'); await userEvent.type(screen.getByLabelText('输出单价 / 1M'), '2')
  fireEvent.submit(dialog)
  expect(await screen.findByText(kind === 'channels' ? '请先创建渠道并配置模型映射' : '该渠道没有可定价的上游模型，请先配置模型映射')).toBeInTheDocument()
})
